### ISSUE TITLE
How to build this arm64 toolchain?

### ISSUE THREAD

**Issue by m4coding** [Saint-Theana/android-ndk-aide-aarch64targeted-arm64hosted-api28-standalonetoolchain#1]

**Comment by Saint-Theana** [comment]
#look at https://github.com/Saint-Theana/ndk_for_android
git clone https://github.com/Saint-Theana/ndk_for_android
cd ndk_for_android
build/tools/make_standalone_toolchain.py --arch arm64 --api 28 --stl libc++ --install-dir /opt/toolchain --verbose -v  --force
